services:

  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ukol
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  migrate:
    build:
      context: .
      dockerfile: libs/data/Dockerfile
    environment:
      - DB_CONNECTION_STRING=postgresql://postgres:postgres@db:5432/ukol
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - DB_CONNECTION_STRING=postgresql://postgres:postgres@db:5432/ukol
      - PORT=3333
    ports:
      - 3333:3333
    depends_on:
      - db
      - migrate

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        BUILD_ENV: development
        RUN_COMMAND: debug
    ports:
      - 8080:8080
      - 9229:9229
    environment:
      - GQL=http://localhost:3333/graphql
      - API=http://localhost:3333/api

volumes:
  node-modules: null
  db:
    driver: local